# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Faster SO2 Design value
#'
#' @param x An impact matrix.
#' @export
faster_dv <- function(x) {
    .Call(`_aermod_faster_dv`, x)
}

